# Version information.
settings_version:   0.1.0
# Info.
program_name:       "Peek-a-Boo"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
# Code embedding settings.
max_embed_ratio:    0.5
min_capacity:       1000
prog_code:          "PICCODER"
byte_chunk:         50000
secret_folder:      "./secrets"
thumb_folder:       "./images"
